---
# tasks file for openvpn

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - openvpn

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - openvpn

- name: Create OpenVPN client configuration file
  become: yes
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart openvpn
  when: openvpn_client
  tags:
    - openvpn
